Add dynamic twitter content to candidate page, rewrite candidate page
googleinterns/voter-central pull request #18
Opened 2020-07-16 22:46 UTC by ganewman

… to work using templates.

### What is a quick description of the change?

This PR displays the twitter feed for a given candidate on the candidate page using the Twitter for Website Timeline widget.
The candidate's twitter handle is passed along with other official candidate info.

This PR also reorganizes many of the functions in the `script.js` file so that candidate information is displayed on the candidate page using AngularJS templates. Information is passed through the candidate page's `scope`, rather than being inserted using JavaScript. 

This same process will eventually be carried out for the directory page as well.

### Is this fixing an issue?

none

### Are there more details that are relevant?

none

### Check lists (check `x` in `[ ]` of list items)

- [  ] Test written/updating
- [ ] Tests passing
- [X] Coding style (indentation, etc)

Please explain why any are not present, if any.

### Any additional comments?

2020-07-17 15:42 UTC, kellyktan approved these changes

2020-07-17 15:42 UTC, kellyktan commented on project/src/main/webapp/candidate-page/candidate-page.template.html
> +</div>
newlines

2020-07-17 16:04 UTC, KathyFeiyang requested changes

2020-07-17 16:04 UTC, KathyFeiyang commented on project/src/main/webapp/candidate-page/candidate-page.component.js
> +
nit: remove this empty line

2020-07-17 16:04 UTC, KathyFeiyang commented on project/src/main/webapp/candidate-page/candidate-page.component.js
> +}
nit: add new line

2020-07-17 16:04 UTC, KathyFeiyang commented on project/src/main/webapp/candidate-page/candidate-page.template.html
> +</div>
nit: add new line

2020-07-17 16:04 UTC, KathyFeiyang commented on project/src/main/webapp/script.js
> +}
nit: add new line

2020-07-17 17:17 UTC, ganewman commented on project/src/main/webapp/candidate-page/candidate-page.template.html
> +</div>
Oops! Every time...

2020-07-17 17:50 UTC, KathyFeiyang approved these changes
LGTM!

2020-07-17 20:28 UTC, suparnabarua approved these changes

2020-07-17 20:28 UTC, suparnabarua commented on project/src/main/webapp/candidate-page/candidate-page.component.js
> +  // Add 2 components of information to the scope.
nit. Remove redundant comment

2020-07-20 18:25 UTC, tjyoung99 approved these changes

2020-07-20 18:31 UTC, merged