Add feature to list all elections on the directory page.
googleinterns/voter-central pull request #21
Opened 2020-07-20 19:20 UTC by ganewman

### What is a quick description of the change?

This PR adds a "List All Elections" button to the landing page, which allows the user to view all elections stored in the database on the directory page. It also refactors the data servlet. Going forward, election information will generally be retrieved as follows:

- Retrieve a list of all elections from the database
- Check if the `listAll` parameter is true; if it is, return the list of all elections.
- If the parameter is false, use the Civic Information API to determine whether each election is relevant to the provided address. Return a list of only the relevant elections.

### Is this fixing an issue?

none

### Are there more details that are relevant?

none

### Check lists (check `x` in `[ ]` of list items)

- [  ] Test written/updating
- [X] Tests passing
- [X] Coding style (indentation, etc)

Please explain why any are not present, if any.

### Any additional comments?

2020-07-20 19:51 UTC, suparnabarua requested changes

2020-07-20 19:51 UTC, suparnabarua commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +    if (listAll) {
So this is just always returning true for now? If so, you can just do return true with the TODO right above it

2020-07-20 19:51 UTC, suparnabarua commented on project/src/main/webapp/index.html
> +        <input type="hidden" name="listAll" value="true"/>
I would change the element name from listAll to listAllElections to make it more clear what you're listing

2020-07-20 19:55 UTC, KathyFeiyang requested changes

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +    List<Election> elections = new ArrayList<>();
nit: maybe still name this variable `electionsData`, as you're using `electionsData` on line 60.

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +          (List<Boolean>) election.getProperty("candidateIncumbency"));
should align the indentation

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +          (Date) election.getProperty("date"), positions));
There should be at least 8 spaces of indent, since the date is two-layer-nested. Maybe align `election` and `(Date)...`

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +   * Takes an {@code Entity} object which represents an elections, and returns true if
nit: "represents an election"

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +   * this election is deemed relevant to the given address. If the {@code listAll} parameter
nit: "{@code address}" instead of "address"

2020-07-20 19:55 UTC, KathyFeiyang commented on project/src/main/webapp/index.html
> +        <input type="hidden" name="address" value="default"/>
Maybe make the "value" attribute more descriptive, such as "street address"/"residence address"

2020-07-20 20:13 UTC, KathyFeiyang commented on project/src/main/webapp/index.html
>        </form>
Why are there two forms, while some inputs are hidden?

2020-07-20 22:13 UTC, KathyFeiyang approved these changes
LGTM pending these changes!

2020-07-20 22:13 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +                                    candidateIncumbencyData);
extra small nit: align `candidatePositionsData` with `candidateIncumbencyData`

2020-07-20 22:13 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +                                (Date) election.getProperty("date"), positions));
extra small nit: align the parameters, meaning that `e` should be aligned with `(`

2020-07-20 22:13 UTC, KathyFeiyang commented on project/src/main/java/com/google/sps/servlets/DataServlet.java
> +    System.out.println(candidatePositions);
nit: remove this line

2020-07-21 13:53 UTC, suparnabarua approved these changes
LGTM pending open comments

2020-07-21 13:58 UTC, kellyktan approved these changes
LGTM pending open comments

2020-07-22 20:43 UTC, tjyoung99 approved these changes

2020-07-23 04:27 UTC, merged