Implement general UI features using Bootstrap.
googleinterns/voter-central pull request #24
Opened 2020-07-23 20:24 UTC by ganewman

### What is a quick description of the change?

- Use BootstrapCDN to add Bootstrap and related JS files as a dependency on all HTML files.
- Rewrite HTML files to use Bootstrap gridding features to align different sections of website.

This PR is a draft, and will include more changes in the future. When changes are made, this description will be updated!

### Is this fixing an issue?

none

### Are there more details that are relevant?

{Fill in here or 'none'}

### Check lists (check `x` in `[ ]` of list items)

- [  ] Test written/updating
- [  ] Tests passing
- [  ] Coding style (indentation, etc)

Please explain why any are not present, if any.

### Any additional comments?

2020-07-23 20:51 UTC, suparnabarua requested changes

2020-07-23 20:51 UTC, suparnabarua commented on project/src/main/webapp/style.css
> +}
nit new line

2020-07-23 20:51 UTC, suparnabarua commented on project/src/main/webapp/index.html
> +    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity=
You're reusing the various script srces a lot. Consider making them shared variables?

2020-07-24 14:26 UTC, KathyFeiyang requested changes

2020-07-24 14:26 UTC, KathyFeiyang commented on project/src/main/webapp/candidate.html
> +        crossorigin="anonymous">
nit: maybe align the parameters `rel`, `integrity`, `crossorigin`

2020-07-28 15:46 UTC, kellyktan requested changes

2020-07-28 15:46 UTC, kellyktan commented on project/src/main/webapp/candidate.html
> +      </div>
Should this be indented?

2020-07-28 15:46 UTC, kellyktan commented on project/src/main/webapp/candidate.html
> +      </div>
Same for the other files.

2020-07-28 16:24 UTC, suparnabarua approved these changes

2020-07-28 18:25 UTC, KathyFeiyang approved these changes
LGTM pending changes for existing comments!

2020-07-28 18:25 UTC, KathyFeiyang commented on project/src/main/webapp/index.html
> +                      required/>
nit: reduce indentation

2020-07-29 18:29 UTC, tjyoung99 approved these changes

2020-07-29 20:44 UTC, kellyktan approved these changes

2020-07-30 00:37 UTC, merged